name: Reusable Workflows!

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yaml

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.test.outputs.build_id }}"

