name: Continue on Error

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: my-step-id
        run: exit 1
        continue-on-error: true
      - run: echo "$STEP_INFO"
        env:
          STEP_INFO: ${{ toJSON(steps.my-step-id) }}
