name: Create Issue

on: workflow_dispatch

jobs:
  issues-permission:
    permissions:
      issues: write

    runs-on: ubuntu-latest

    steps:
      - run: gh issue create --repo "${{ github.repository }}" --title "Test Issue" --body "Testing issue creation"
        env:
          GH_TOKEN: ${{ github.token }}

  issue-contents-permission:
    permissions:
      contents: read
      issues: write

    runs-on: ubuntu-latest

    steps:
      - run: gh issue create --repo "${{ github.repository }}" --title "Test Issue" --body "Testing issue creation"
        env:
          GH_TOKEN: ${{ github.token }}