name: Inputs

on:
  workflow_dispatch:
    inputs:
      one:
      two:
      three:
      four:
      five:
      six:
      seven:
      eight:
      nine:
      ten:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - run: echo $INPUTS
        env:
          INPUTS: ${{ toJSON(inputs) }}
      - name: Process     
      - run: echo $INPUT_ONE
        env:
          INPUT_ONE: ${{ fromJSON(inputs.one)['one'] }}
