name: Test ESM with github-script

on:
  workflow_dispatch:

jobs:
  esm-dynamic-imports:
    name: Try ESM dynamic imports
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: thboop/github-script@d2ed94b14f4e194b2afdd7fe2af49e0d93c42d92
        with:
          script: |
            try {
              console.log('Before dynamic import')
              const { default: printStuff } = await import('${{ github.workspace }}/src/print-stuff.js')
              console.log('After dynamic import')
              await printStuff()
              console.log('At the end')
            } catch (error) {
              console.error('Threw an error!')
              throw error
            }
