name: Hello 🌎

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true
        default: 'World'
        type: string

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello $NAME"
        env:
          NAME: ${{ github.event.inputs.name }}
