name: Job Conditionals

on: workflow_dispatch

jobs:
  a:
    if: true
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  b:
    if: false
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  c:
    if: false
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  
  d:
   needs: [a, b, c]
   if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
   runs-on: ubuntu-latest

   steps:
    - run: echo "Hello world"
