name: Labelled

on:
  issues:
    types: [labeled]

jobs:
  skip:
    if: "${{ contains(github.event.label.name, 'needs: triage') }}"
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello label"

  emojis:
    runs-on: ubuntu-latest
    steps:
      - run: echo "⌚"
        if: "${{ contains(github.event.label.name, '⌚') }}"
      
      - run: echo ":watch:"
        if: "${{ contains(github.event.label.name, ':watch:') }}"

  event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_EVENT"
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
