name: Rate Limit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest, ubuntu-24.04-arm ]

    steps:
      - run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit
        env:
          GH_TOKEN: ${{ github.token }}
