name: 🗃 Push Filter

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'


jobs:
  build:
#     if: contains(github.ref, 'pull')   # Only run this workflow if the ref contains 'pull'
  
    runs-on: ubuntu-latest
  
    steps:
      - run: echo hello world 🗺, your branch is ${{ github.ref }}
