name: It's Reusable!

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: false
        type: string
    outputs:
      build_id:
        description: 'A build ID'
        value: 456

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello ${{ inputs.username }}"